FORMAT: 1A


# Habit Tracker API

A simple API allowing consumers to manage habits.

# Habit Tracker API root [/]

This resource offers metadata (API version and list of endpoints) about the APIs.

## Retrieve the entry point [GET]

+ Response 200 (application/json)

        {
            "apiVersion": "0.0.1",
            "endpoints": [
                "/",
                "/login"
            ]
        }


# Group Authentication and Account management

Endpoints related to the authentication process and the management of the account.

## Registration [/register]

### Register [POST]

Register to the Habit Tracker API.
Returns the JWT token.

+ name (string) - The user's name
+ email (string) - The user's email
+ password (string) - The user's password

+ Request Register (application/json)

        {
            "name": "Test",
            "email": "test@gmail.com",
            "password": "test"
        }

+ Response 201 (application/json)

        {
            "statusCode": 201,
            "error": false,
            "token": "jwt-token"
        }

## Login [/login]

### Login [GET]

Get the JWT token to access to the protected API endpoints.

Basic authentication.
- Basic authentication username: email
- Basic authentication password: password

+ Request Login (application/json)

    + Headers

            Authorization: Basic dGVzdEBnbWFpbC5jb206dGVzdA==


+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
            "token": "jwt-token"
        }

## Account management [/user]

### View information about the account [GET]

Retrieve information on the logged in user account.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
            "user": {
                "name": "Test",
                "email": "test@gmail.com",
                "registrationDate": "2020-11-20T00:00:00.000Z"
            }
        }

### Delete the account [DELETE]

Delete the account of the logged in user.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
        }


# Group Habits

Resources related to Habits in the API.

## Habit collection [/habits{?limit}{?skip}{?category}{?filter}]

This resource represents a collection of habits.

### List all habits [GET]

Retrive the list of habits of the logged in user.

+ Parameters

    + limit (number, optional) - The maximum number of habits to return.
        + Default: `50`
    + skip (number, optional) - The number of habits to skip.
        + Default: `0`
    + category (string, optional) - The category of habits to return. By default returns all the habits.
        + Default: ``
    + filter (enum, optional) - The type of habits to return (valid options are `all`, `archived`, `active`).
        + Default: `active`

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
            "habits": [
                {
                    "id": "6086e696cdcf2b0858e8e8b5",
                    "name": "Study",
                    "creationDate": "2021-02-02T00:00:00.000Z",
                    "category": "Learning",
                    "archived": false
                },
                {
                    "id": "6086e696cdcf2b0858e8e8b6",
                    "name": "Run",
                    "creationDate": "2021-03-05T00:00:00.000Z",
                    "category": "Sport",
                    "archived": false
                },
                {
                    "id": "6086e696cdcf2b0858e8e8b7",
                    "name": "Read",
                    "creationDate": "2021-03-07T00:00:00.000Z",
                    "category": "Learning",
                    "archived": false
                }
            ]
        }

### Create a new habit [POST]

Create a new habit.
It takes a JSON object containing the habit name and category.
It returns the newly created habit.

+ name (string) - The habit name
+ category (string) - The habit category

+ Request Create new Habit (application/json)

        {
            "name": "Run",
            "category": "Sport"
        }

+ Response 201 (application/json)

        {
            "statusCode": 201,
            "error": false,
            "habit": {
                "id": "6086e696cdcf2b0858e8e8b6",
                "name": "Run",
                "creationDate": "2021-03-05T00:00:00.000Z",
                "category": "Sport",
                "archived": false
            }
        }

## Habit [/habits/{habit_id}]

This resource represents a single habit.

+ Parameters
    + habit_id (string) - The ID of the habit.

### View the habit details [GET]

Retrive the habit details.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
            "habit": {
                "id": "6086e696cdcf2b0858e8e8b6",
                "name": "Run",
                "creationDate": "2021-03-05T00:00:00.000Z",
                "category": "Sport",
                "archived": false
            }
        }

### Update the habit [PUT]

Update the habit.
It takes a JSON object containing at least one of the following fields: `name`, `category`, `archived`.

+ name (string) - The habit name
+ category (string) - The habit category
+ archived (boolean) - Whether the habit is archived or active

+ Request Update Habit name (application/json)

        {
            "name": "Run",
        }

+ Request Update Habit category (application/json)

        {
            "category": "Sport",
        }

+ Request Archive Habit (application/json)

        {
            "archived": true,
        }

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
        }

### Delete the habit [DELETE]

Delete the habit.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false
        }

## Habit history [/habits/{habit_id}/history]

This resource represents the history of a single habit.

+ Parameters
    + habit_id (string) - The ID of the habit.

### View the history of the habit [GET]

Retrieve the history of the habit.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
            "history": [
                {
                    "id": "6086e696cdcf2b0858e8e8b6",
                    "date": "2021-03-05T00:00:00.000Z",
                    "type": 'completed'
                },
                {
                    "id": "6086e696cdcf2b0858e8e8b7",
                    "date": "2021-03-06T00:00:00.000Z",
                    "type": 'skipped'
                },
                {
                    "id": "6086e696cdcf2b0858e8e8b8",
                    "date": "2021-03-07T00:00:00.000Z",
                    "type": 'completed'
                }
            ]
        }

### Add a new entry to the habit history [POST]

Add a new entry to the habit history.
It takes a JSON object containing the date and the type of the history entry.

+ date (string) - The date of the history entry (ISO format)
+ type (string) - The type of the history entry (`completed`, `skipped`)

+ Request Add new entry to the Habit history (application/json)

        {
            "date": "2021-03-08T00:00:00.000Z",
            "type": "completed"
        }

+ Response 201 (application/json)

        {
            "statusCode": 200,
            "error": false
        }


## Habit history entry [/habits/{habit_id}/history/{date}]

This resource represents a single history entry of a habit.

+ Parameters
    + habit_id (string) - The ID of the habit.
    + date (string) - The date of the history entry formatted as YYYY-MM-DD.

### Update the entry of the habit history [PUT]

Update (the type of) an entry of the habit history.
It takes a JSON object containing the new type of the history entry.

+ type (string) - The type of the history entry (`completed`, `skipped`)

+ Request Update entry of the Habit history (application/json)

        {
            "type": "skipped"
        }

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false
        }

### Delete the entry from the habit history [DELETE]

Delete the entry from the habit history.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false
        }


# Group Statistics

Resources related to statistics in the API.

## General statistics [/stats]

This resource represents the general statistics of the logged in user.

### Get general statistics [GET]

Retrive general statistics about the logged in user.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
            "stats": {
                "habitCount": 3,
                "TODO": "TODO: other stats"
            }
        }

## Habit statistics [/stats/{habit_id}]

This resource represents the statistics of a single habit.

+ Parameters
    + habit_id (string) - The ID of the habit.

### Get habit statistics [GET]

Retrive statistics about the habit.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
            "stats": {
                "bestStreak": 5,
                "TODO": "TODO: other stats"
            }
        }


# Group Categories

Resources related to Categories in the API.

## Category collection [/categories]

This resource represents a collection of categories.

### List all categories [GET]

Retrive the list of categories of habits of the logged in user.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false,
            "categories": [
                "Learning",
                "Sport",
                "Productivity"
            ]
        }

### Create a new category [POST]
TODO probabilmente non serve
Create a new category.
It takes a JSON object containing the category name.

+ name (string) - The category name

+ Request Create new Category (application/json)

        {
            "name": "Health"
        }

+ Response 201 (application/json)

        {
            "statusCode": 201,
            "error": false
        }

## Category [/categories/{category_name}]

This resource represents a single habit.

+ Parameters
    + category_name (string) - The name of the category.

### Update category name [PUT]

Update the category name.
It takes a JSON object containing the new category name.

+ name (string) - The new name of the category

+ Request Update category name (application/json)

        {
            "name": "Misc"
        }

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false
        }

### Delete the category [DELETE]

Delete the entry from the habit history.
TODO: Only if the category is not used (però per ora non ho una collection di category).
TODO probabilmente non serve.

+ Response 200 (application/json)

        {
            "statusCode": 200,
            "error": false
        }
